# Generated by Django 3.2.25 on 2024-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ingredient',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
    ]
