# Generated by Django 3.2.25 on 2024-08-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredient',
            new_name='Ingredients',
        ),
    ]
