# Generated by Django 3.2.25 on 2024-08-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
